import type {
  BoxFeatureParameters,
  BodyCopyFeatureParameters,
  CylinderFeatureParameters,
  ExtrudeFeatureParameters,
  FastenerFeatureParameters,
  HelixFeatureParameters,
  HoleFeatureParameters,
  LoftFeatureParameters,
  MoveFeatureParameters,
  RevolveFeatureParameters,
  SweepFeatureParameters,
  ThreadFeatureParameters,
  Shape2D,
  Vector3,
} from "@/types";

export interface SketchProfilePoint {
  x: number;
  y: number;
}

export interface SketchLineEntry {
  line_id: string;
  start_point_id: string;
  end_point_id: string;
  // Vertex unification (Phase 5)
  start_vertex_id?: string;
  end_vertex_id?: string;
  start_x: number;
  start_y: number;
  end_x: number;
  end_y: number;
  constraint: "horizontal" | "vertical" | null;
  // Reference-only construction lines render dashed and don't seal
  // profile loops. Defaults to false on older saves via the schema.
  is_construction: boolean;
}

export interface SketchCircleEntry {
  circle_id: string;
  // Vertex unification (Phase 5)
  center_vertex_id?: string;
  center_x: number;
  center_y: number;
  radius: number;
  is_construction: boolean;
}

export interface SketchVertexEntry {
  point_id: string;
  /** vertex-N ID from Phase 4 vertex unification. */
  vertex_id?: string;
  // "endpoint" / "center" / "projected" — see `SketchVertexScene`
  // for the renderer-side meaning of each value.
  kind: "endpoint" | "center" | "projected";
  x: number;
  y: number;
  is_fixed: boolean;
  // ── Vertex unification (Phase 1-2) ─────────────────────────
  geometry_owner_ids?: string[];
  is_projected?: boolean;
  source_type?: string;
  source_feature_id?: string;
  source_edge_id?: string;
}

export interface SketchDimensionEntry {
  dimension_id: string;
  kind:
    | "line_length"
    | "circle_radius"
    | "arc_radius"
    | "polygon_radius"
    | "angle"
    | "line_angle"
    | "line_line_distance"
    | "circle_center_distance"
    | "circle_line_distance"
    | "point_distance";
  entity_id: string;
  secondary_entity_id: string;
  value: number;
  expression: string;
  /** When true, this is a reference-only (driven) dimension. */
  driven?: boolean;
  /** For circle_radius: "" = diameter display (default), "radius" = radius display. */
  display_as?: string;
  /** Optional sketch-local label placement override. */
  label_x?: number | null;
  label_y?: number | null;
  /** ID of the constraint this dimension enforces (Phase 3). */
  constraint_id?: string;
}

export interface SketchLineRelationEntry {
  relation_id: string;
  kind: "equal_length" | "perpendicular" | "parallel";
  first_line_id: string;
  second_line_id: string;
}

export interface SketchProfileRegionEntry {
  profile_id: string;
  kind: "polygon" | "circle";
  point_ids: string[];
  line_ids: string[];
  points: SketchProfilePoint[];
  inner_loops: SketchProfilePoint[][];
  source_circle_id: string | null;
  center_x: number;
  center_y: number;
  radius: number;
}

// Transient state for the in-progress Mirror tool. Mirrors the
// `pending_mirror` field on the C++ `SketchFeatureParameters`.
// Present (non-null) only while the user has the Mirror tool
// open; the UI uses presence as the trigger to show the floating
// panel.
export interface PendingMirrorEntry {
  axis_line_id: string | null;
  object_ids: string[];
  // Generated geometry, regenerated by the core whenever the
  // axis or objects change. Rendered as dashed translucent
  // previews in the viewport (via the `is_preview` flag on the
  // viewport line / circle primitives).
  generated_lines: Array<{
    line_id: string;
    start_point_id: string;
    end_point_id: string;
    start_x: number;
    start_y: number;
    end_x: number;
    end_y: number;
    is_construction: boolean;
  }>;
  generated_circles: Array<{
    circle_id: string;
    center_x: number;
    center_y: number;
    radius: number;
    is_construction: boolean;
  }>;
}

// 2D arc entry stored on the sketch feature. Mirrors C++ `SketchArc`.
// Endpoints share the SketchPoint graph via `start_point_id` /
// `end_point_id`; `(center_x, center_y, radius, ccw)` are cached so
// the renderer can sample without recomputing the circumcircle. v1
// freezes arc shape at creation; the points are stored with
// `is_fixed=true` in the points table.
export interface SketchArcEntry {
  arc_id: string;
  start_point_id: string;
  end_point_id: string;
  // Vertex unification (Phase 5)
  start_vertex_id?: string;
  end_vertex_id?: string;
  center_vertex_id?: string;
  center_x: number;
  center_y: number;
  radius: number;
  start_x: number;
  start_y: number;
  end_x: number;
  end_y: number;
  ccw: boolean;
  is_construction: boolean;
}

// Regular polygon stored on the sketch feature. Mirrors C++ `SketchPolygon`.
export interface SketchPolygonEntry {
  polygon_id: string;
  center_x: number;
  center_y: number;
  radius: number;
  sides: number;
  mode: string;
  start_x: number;
  start_y: number;
  end_x: number;
  end_y: number;
  is_construction: boolean;
}

// Parametric corner fillet on the sketch. Mirrors C++ `SketchFillet`.
// `corner_x` / `corner_y` are denormalized so the corner point can
// be re-emitted into the points table even when no other entity
// references it; the core refreshes them on every recompute.
// `radius` is the user-controlled parameter; everything else is
// generated geometry kept in sync with `lines` and `arcs`.
export interface SketchFilletEntry {
  fillet_id: string;
  corner_point_id: string;
  corner_x: number;
  corner_y: number;
  line_a_id: string;
  line_b_id: string;
  trim_a_point_id: string;
  trim_b_point_id: string;
  arc_id: string;
  radius: number;
}

export interface SketchFeatureParameters {
  plane_id: string;
  plane_frame: {
    origin: Vector3;
    x_axis: Vector3;
    y_axis: Vector3;
    normal: Vector3;
  } | null;
  active_tool: SketchTool;
  lines: SketchLineEntry[];
  circles: SketchCircleEntry[];
  arcs: SketchArcEntry[];
  polygons: SketchPolygonEntry[];
  fillets: SketchFilletEntry[];
  points: SketchVertexEntry[];
  dimensions: SketchDimensionEntry[];
  line_relations: SketchLineRelationEntry[];
  // Midpoint anchors. Empty on older saves; the schema fills in [].
  midpoint_anchors: SketchMidpointAnchorEntry[];
  // Point-line anchors: parametric `t` position of a bound point
  // along a host line. Generalization of midpoint anchors used by
  // line-body and sub-segment midpoint snaps. Empty on older saves.
  point_line_anchors: SketchPointLineAnchorEntry[];
  // Standalone projected points placed by the Project tool. These
  // are *not* line / arc / circle endpoints — they live in their own
  // collection so `rebuild_sketch_points` can re-emit them on every
  // recompute. Empty on older saves; the schema defaults to [].
  projected_points: SketchProjectedPointEntry[];
  // Body face / edge ids that have already been projected onto this
  // sketch. Used by the Project tool to short-circuit duplicate
  // clicks. Empty on older saves; the schema defaults to [].
  projected_sources: string[];
  // Live links between body sources and the sketch entities the
  // Project tool generated from them. Re-resolved by the core's
  // `refresh_sketch_projections` pass on every recompute so that
  // edits to the upstream geometry move the projected sketch
  // entities in lockstep. Empty on older saves; the schema
  // defaults to [].
  projections: SketchProjectionEntry[];
  profiles: SketchProfileRegionEntry[];
  // Optional pending mirror tool state. Null when no mirror is in
  // progress.
  pending_mirror: PendingMirrorEntry | null;
}

export interface SketchMidpointAnchorEntry {
  anchor_id: string;
  point_id: string;
  line_id: string;
}

export interface SketchPointLineAnchorEntry {
  anchor_id: string;
  point_id: string;
  line_id: string;
  t: number;
}

// One standalone sketch point produced by the Project tool. The
// canonical form is the `SketchVertexEntry` re-emitted into the
// sketch's `points` array (with `kind = "projected"` and
// `is_fixed = true`); this entry tells the core where to put it.
// `source_id` is the body vertex id (`<body>:vertex:<index>`) used
// for idempotency.
export interface SketchProjectedPointEntry {
  point_id: string;
  source_id: string;
  x: number;
  y: number;
}

// One live-link record produced by the Project tool. The core's
// `refresh_sketch_projections` pass re-resolves `source_id` against
// the latest body geometry on every recompute and patches the
// matching `generated_*_ids` entities in place. The UI doesn't
// dispatch these directly — they ride along in the document state
// for round-trip serialization and so future "fix broken
// projection" UX has a place to point at.
export interface SketchProjectionEntry {
  projection_id: string;
  source_id: string;
  source_kind: "face" | "edge" | "vertex" | "profile";
  generated_line_ids: string[];
  generated_circle_ids: string[];
  generated_arc_ids: string[];
  // Empty unless `source_kind === "vertex"`.
  generated_point_id: string;
  // True when the most recent recompute couldn't re-resolve the
  // source (body deleted, curve type changed). The generated
  // entities stay frozen at their last-known coords; the parent
  // sketch surfaces a feature-level dependency_broken warning.
  dependency_broken: boolean;
  dependency_warning: string;
}

export interface FilletFeatureParameters {
  target_body_id: string;
  edge_ids: string[];
  radius: number;
  // True while the fillet is in its floating-panel "pending" phase.
  // The viewport keeps emitting edge ids from the *pre*-fillet body
  // topology so picks remain stable while the user toggles edges.
  // Confirm flips this to false; the body's edge identity then
  // follows the post-fillet topology like any other feature.
  is_pending: boolean;
}

export interface ChamferFeatureParameters {
  target_body_id: string;
  edge_ids: string[];
  distance: number;
  // See FilletFeatureParameters.is_pending — same semantics.
  is_pending: boolean;
}

export interface ShellFeatureParameters {
  target_body_id: string;
  removed_face_ids: string[];
  thickness: number;
  is_pending: boolean;
}

// Parametric construction plane parameters. The cached
// `plane_frame` is the world-space frame the core re-derives on
// every recompute, so the UI can read it without having to invert
// the source relationship itself.
export interface ConstructionPlaneFeatureParameters {
  plane_type: "offset" | "midplane" | "tangent" | "angle";
  source_plane_id: string;
  source_plane_ids: string[];
  source_axis_id: string;
  offset: number;
  angle_degrees: number;
  plane_frame: {
    origin: Vector3;
    x_axis: Vector3;
    y_axis: Vector3;
    normal: Vector3;
  };
}

export interface ConstructionAxisFeatureParameters {
  source_id: string;
  source_kind: "edge" | "sketch_line" | "construction_axis";
  start: Vector3;
  end: Vector3;
}

export interface ConstructionPointFeatureParameters {
  source_id: string;
  source_kind: "vertex" | "sketch_point";
  position: Vector3;
}

export interface PluginFeatureParameters {
  plugin_id: string;
  feature_type: string;
  schema_version: number;
  is_pending: boolean;
  display_name: string;
  parameters_summary: string;
  parameters: Record<string, unknown>;
  geometry: Array<{
    operation: "add" | "subtract";
    primitive:
      | "box"
      | "rounded_box"
      | "tapered_rounded_box"
      | "cylinder"
      | "profile_extrude"
      | "rounded_rect_profile_sweep";
    x: number;
    y: number;
    z: number;
    width: number;
    depth: number;
    height: number;
    radius?: number;
    top_width?: number;
    top_depth?: number;
    top_radius?: number;
    top_offset_x?: number;
    top_offset_y?: number;
    profile_plane?: "xy" | "xz" | "yz";
    extrude_x?: number;
    extrude_y?: number;
    extrude_z?: number;
    path_width?: number;
    path_depth?: number;
    path_radius?: number;
    profile_points?: Array<{ u: number; v: number }>;
  }>;
}

export interface FeatureEntry {
  feature_id: string;
  kind: string;
  name: string;
  status: string;
  // Optional in serialized form for forward-compat with older
  // documents; the schema defaults missing values to false. When the
  // flag is true the feature is hidden from the viewport but still
  // shown in the timeline / hierarchy (dimmed) so the user can
  // unsuppress it.
  suppressed?: boolean;
  // True when an upstream reference (face-based sketch plane, etc.)
  // can no longer be resolved. Defaults to false so older saves and
  // freshly-built features behave normally.
  dependency_broken?: boolean;
  // Human-readable explanation, surfaced as the timeline tooltip.
  dependency_warning?: string;
  parameters_summary: string;
  box_parameters: BoxFeatureParameters | null;
  cylinder_parameters: CylinderFeatureParameters | null;
  extrude_parameters: ExtrudeFeatureParameters | null;
  loft_parameters: LoftFeatureParameters | null;
  revolve_parameters: RevolveFeatureParameters | null;
  sweep_parameters: SweepFeatureParameters | null;
  hole_parameters: HoleFeatureParameters | null;
  helix_parameters: HelixFeatureParameters | null;
  thread_parameters: ThreadFeatureParameters | null;
  fastener_parameters: FastenerFeatureParameters | null;
  move_parameters: MoveFeatureParameters | null;
  body_copy_parameters: BodyCopyFeatureParameters | null;
  plugin_feature_parameters?: PluginFeatureParameters | null;
  sketch_parameters: SketchFeatureParameters | null;
  fillet_parameters: FilletFeatureParameters | null;
  chamfer_parameters: ChamferFeatureParameters | null;
  shell_parameters: ShellFeatureParameters | null;
  // Optional in serialized form so older `.polysmith` saves load
  // cleanly. Present on `construction_plane` features.
  construction_plane_parameters?: ConstructionPlaneFeatureParameters | null;
  construction_axis_parameters?: ConstructionAxisFeatureParameters | null;
  construction_point_parameters?: ConstructionPointFeatureParameters | null;
}

// `project` is a modal tool, not a shape: while it's active the
// viewport routes face / edge / vertex clicks to the matching
// `project_*_into_sketch` IPC commands instead of the normal
// selection. Kept outside `Shape2D` so the shape unions don't grow
// a non-shape value.
export type SketchTool = "select" | Shape2D | "project" | "dimension";

/** Rectangle creation modes for the split tool button. */
type RectangleToolMode =
  | "corner_corner"
  | "center_point"
  | "three_point";

/** Arc creation modes for the split tool button. */
type ArcToolMode = "three_point" | "center_start_end";

/** Circle creation modes for the split tool button.
 *  `tangent_two_lines` and `tangent_three_lines` are reserved for
 *  future core support — selecting them has no effect yet. */
type CircleToolMode =
  | "center_radius"
  | "two_point"
  | "three_point"
  | "tangent_two_lines"
  | "tangent_three_lines";

/** Polygon creation modes for the split tool button. */
type PolygonToolMode = "circumscribed" | "inscribed" | "edge";

/** Dimension tool modes for the split tool button.
 *  Only "auto" is functional today; the rest are reserved for
 *  future ISO drawing-sheet dimensioning. */
export type DimensionToolMode =
  | "auto"
  | "linear"
  | "aligned"
  | "angular"
  | "radius"
  | "diameter"
  | "ordinate"
  | "jogged_radial"
  | "arc_length"
  | "curve_min_max"
  | "baseline"
  | "chain"
  | "tidy_up"
  | "arrange"
  | "flip_arrows"
  | "match"
  | "dimension_break";