// Regression tests for the sketch Text tool's core pipeline: glyph
// expansion into generated sketch lines, complete profile-region sets
// (outer + hole), deterministic re-expansion, TNP-friendly id stability
// across parametric edits, generated-entity guards, deletion through
// selection, undo, and extrude-from-text (the emboss-ready contract).
//
// Profile assertions use profiles_match from sketch_test_utils.h
// (complete region-set matching, not presence-only). Glyph geometry
// comes from the embedded DejaVu Sans fallback in TKService, so the
// tests need no font file on disk.

#include <algorithm>
#include <cmath>
#include <filesystem>
#include <iostream>
#include <set>
#include <string>
#include <vector>

#include <BRepGProp.hxx>
#include <GProp_GProps.hxx>
#include <TopAbs.hxx>
#include <TopExp.hxx>
#include <TopExp_Explorer.hxx>
#include <TopoDS.hxx>

#include "core/document/document.h"
#include "core/geometry/body_compiler.h"
#include "core/sketch/dof_counter.h"
#include "core/text_engine.h"
#include "core/viewport/viewport.h"
#include "sketch_test_utils.h"

namespace {

using polysmith::core::DocumentManager;
using polysmith::core::DocumentState;
using polysmith::core::DofStatus;
using polysmith::core::SketchFeatureParameters;
using polysmith::core::SketchText;
using polysmith::core::compile_bodies;

bool expect(bool condition, const char* message) {
  if (condition) return true;
  std::cerr << message << "\n";
  return false;
}

SketchFeatureParameters sketch_params(const DocumentState& document) {
  for (const auto& feature : document.feature_history) {
    if (feature.kind == "sketch" && feature.sketch_parameters.has_value()) {
      return feature.sketch_parameters.value();
    }
  }
  throw std::runtime_error("no sketch feature in document");
}

// The one text entity in the sketch (tests add exactly one).
const SketchText& only_text(const SketchFeatureParameters& params) {
  if (params.texts.size() != 1) {
    throw std::runtime_error("expected exactly one sketch text");
  }
  return params.texts[0];
}

std::vector<std::string> generated_line_ids(
    const SketchFeatureParameters& params) {
  std::vector<std::string> ids;
  for (const auto& line : params.lines) {
    if (line.generated_by.has_value()) {
      ids.push_back(line.id);
    }
  }
  return ids;
}

// One closed glyph contour becomes exactly one profile region (outer
// or hole). The expected region count is derived from the engine's own
// contour count for the same string, so the assertion holds for any
// resolved font (DejaVu, Arial, a future bundled font, ...).
int expected_contour_count(const std::string& utf8_text,
                           double height_mm) {
  polysmith::core::text::TextLayout layout;
  std::string error;
  const polysmith::core::text::TextStyle style{
      /*font_path=*/"", height_mm};
  if (!polysmith::core::text::TextEngine::instance().layout(
          utf8_text, 0.0, 0.0, style, &layout, &error)) {
    return -1;
  }
  return static_cast<int>(layout.contours.size());
}

bool test_text_o_profiles() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = "O";
  text.height_mm = 20.0;
  DocumentState document = manager.add_sketch_text(text);
  const auto params = sketch_params(document);

  // Every glyph segment is generated by the text entity.
  const auto generated = generated_line_ids(params);
  if (!expect(!generated.empty(), "O: glyph segments exist")) return false;
  for (const auto& line : params.lines) {
    if (!expect(line.generated_by.has_value() &&
                    line.generated_by.value() == "text:text-1",
                "O: every line is generated by text-1")) {
      return false;
    }
    if (!expect(!line.constraint.has_value(),
                "O: glyph lines carry no constraints")) {
      return false;
    }
  }

  // Exactly two regions: the outer ring and the hole (O has one hole
  // in every resolved font; the count is still derived from the engine
  // so the assertion survives font changes). Build the expected sets
  // from the document itself (the tessellation count is font-dependent)
  // and assert the complete set plus the nesting.
  const int expected_rings = expected_contour_count("O", 20.0);
  if (!expect(expected_rings > 0 && static_cast<int>(params.profiles.size()) ==
                                       expected_rings,
              "O: exactly 2 profiles (outer ring + hole)")) {
    return false;
  }
  std::vector<polysmith::test::ExpectedProfile> expected;
  for (const auto& profile : params.profiles) {
    if (!expect(profile.kind == "polygon" && !profile.source_circle_id,
                "O: both regions are polygon profiles without source circle")) {
      return false;
    }
    expected.push_back({.entity_ids = profile.line_ids,
                        .kind = "polygon",
                        .has_source_circle_id = false});
  }
  std::string reason;
  if (!expect(polysmith::test::profiles_match(document, expected, &reason),
              ("O: complete region set: " + reason).c_str())) {
    return false;
  }

  // Nesting: the outer region lists the hole as an inner loop, the hole
  // lists none. The union of both region id sets is the full glyph set.
  int with_inner = 0;
  std::vector<std::string> union_ids;
  for (const auto& profile : params.profiles) {
    if (!profile.inner_loops.empty()) ++with_inner;
    union_ids.insert(union_ids.end(), profile.line_ids.begin(),
                     profile.line_ids.end());
  }
  if (!expect(with_inner == 1,
              "O: exactly one region carries an inner loop (the hole)")) {
    return false;
  }
  std::sort(union_ids.begin(), union_ids.end());
  auto sorted_generated = generated;
  std::sort(sorted_generated.begin(), sorted_generated.end());
  if (!expect(union_ids == sorted_generated,
              "O: profile regions cover exactly the generated glyph set")) {
    return false;
  }

  // Glyph vertices are fixed; the DOF counter reports generated lines
  // as fully constrained so the viewport renders them in the fixed color.
  for (const auto& vertex : params.vertices) {
    if (vertex.id.rfind("vertex-text-", 0) == 0) {
      if (!expect(vertex.is_fixed, "O: glyph vertices are fixed")) {
        return false;
      }
    }
  }
  if (!expect(polysmith::core::get_entity_dof_status(params, generated[0]) ==
                  DofStatus::FullyConstrained,
              "O: generated lines report fully constrained")) {
    return false;
  }
  return true;
}

bool test_text_ab_profiles() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = "AB";
  text.height_mm = 10.0;
  DocumentState document = manager.add_sketch_text(text);
  const auto params = sketch_params(document);

  // Every glyph contour (outer + holes) becomes exactly one profile
  // region — e.g. DejaVu/Arial: A = outer + 1 hole, B = outer + 2
  // holes → 5 regions. None carry source circles; the outer regions
  // nest their holes.
  const int expected = expected_contour_count("AB", 10.0);
  if (!expect(expected > 0, "AB: engine layout succeeds")) {
    return false;
  }
  if (!expect(static_cast<int>(params.profiles.size()) == expected,
              "AB: one profile region per glyph contour")) {
    return false;
  }
  std::vector<polysmith::test::ExpectedProfile> expected_profiles;
  int with_inner = 0;
  for (const auto& profile : params.profiles) {
    expected_profiles.push_back({.entity_ids = profile.line_ids,
                                 .kind = "polygon",
                                 .has_source_circle_id = false});
    if (!profile.inner_loops.empty()) ++with_inner;
  }
  if (!expect(with_inner >= 1,
              "AB: outer regions nest their holes")) {
    return false;
  }
  std::string reason;
  return expect(
      polysmith::test::profiles_match(document, expected_profiles, &reason),
      ("AB: complete region set: " + reason).c_str());
}

bool test_reexpansion_stability() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = "OK";
  text.height_mm = 12.0;
  DocumentState document = manager.add_sketch_text(text);
  const auto before = sketch_params(document);

  // No-op update with identical values: expansion must reproduce the
  // exact same ids and coordinates (deterministic re-derivation).
  document = manager.update_sketch_text(only_text(before).id, before.texts[0]);
  const auto after = sketch_params(document);

  if (!expect(before.lines.size() == after.lines.size(),
              "stability: segment count unchanged")) {
    return false;
  }
  for (size_t i = 0; i < before.lines.size(); ++i) {
    if (!expect(before.lines[i].id == after.lines[i].id &&
                    before.lines[i].start_vertex_id ==
                        after.lines[i].start_vertex_id &&
                    before.lines[i].end_vertex_id ==
                        after.lines[i].end_vertex_id,
                "stability: ids identical across re-expansion")) {
      return false;
    }
    if (!expect(std::abs(before.lines[i].start_x - after.lines[i].start_x) <
                        1e-9 &&
                    std::abs(before.lines[i].start_y - after.lines[i].start_y) <
                        1e-9 &&
                    std::abs(before.lines[i].end_x - after.lines[i].end_x) <
                        1e-9 &&
                    std::abs(before.lines[i].end_y - after.lines[i].end_y) <
                        1e-9,
                "stability: coordinates identical across re-expansion")) {
      return false;
    }
  }
  return true;
}

bool test_height_edit_keeps_ids_and_scales() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = "O";
  text.height_mm = 20.0;
  DocumentState document = manager.add_sketch_text(text);
  const auto before = sketch_params(document);

  // Height edit scales glyphs 1.5x. The tolerance is proportional to
  // the height, so the tessellation structure — and therefore the
  // generated id set — is unchanged (the TNP contract: profile ids
  // survive, linked extrudes re-snapshot instead of breaking).
  SketchText updated = before.texts[0];
  updated.height_mm = 30.0;
  document = manager.update_sketch_text(updated.id, updated);
  const auto after = sketch_params(document);

  if (!expect(before.lines.size() == after.lines.size(),
              "height: segment count unchanged")) {
    return false;
  }
  for (size_t i = 0; i < before.lines.size(); ++i) {
    if (!expect(before.lines[i].id == after.lines[i].id,
                "height: generated ids unchanged")) {
      return false;
    }
    const double scale = 30.0 / 20.0;
    if (!expect(std::abs(after.lines[i].start_x -
                         before.lines[i].start_x * scale) < 1e-6 &&
                    std::abs(after.lines[i].start_y -
                         before.lines[i].start_y * scale) < 1e-6,
                "height: coordinates scale by exactly 1.5")) {
      return false;
    }
  }

  // Profile ids embed corner coordinates, so they intentionally change
  // under any geometric edit. The TNP-relevant property is the line-id
  // SET: identical generated ids keep every region bounded by the same
  // line set, which is what find_equivalent_profile's containment
  // fallback matches on when re-snapshotting linked extrudes.
  for (const auto& profile : before.profiles) {
    std::set<std::string> want(profile.line_ids.begin(),
                               profile.line_ids.end());
    const auto found = std::find_if(
        after.profiles.begin(), after.profiles.end(),
        [&](const auto& p) {
          std::set<std::string> have(p.line_ids.begin(), p.line_ids.end());
          return have == want;
        });
    if (!expect(found != after.profiles.end(),
                "height: region line-id sets survive the edit")) {
      return false;
    }
  }
  return true;
}

bool test_string_edit_changes_ids() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = "O";
  text.height_mm = 10.0;
  DocumentState document = manager.add_sketch_text(text);
  const auto before = sketch_params(document);
  const auto before_ids = generated_line_ids(before);

  SketchText updated = before.texts[0];
  updated.text = "AB";
  document = manager.update_sketch_text(updated.id, updated);
  const auto after = sketch_params(document);
  const auto after_ids = generated_line_ids(after);

  if (!expect(!after_ids.empty() && !before_ids.empty(),
              "string: both strings generate geometry")) {
    return false;
  }
  return expect(before_ids != after_ids,
                "string: editing the string changes the generated id set");
}

bool test_guards_reject_generated_entities() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = "O";
  text.height_mm = 10.0;
  DocumentState document = manager.add_sketch_text(text);
  const auto params = sketch_params(document);
  const auto generated = generated_line_ids(params);
  const std::string glyph_id = generated.front();

  bool update_threw = false;
  try {
    manager.update_sketch_line(glyph_id, 0.0, 0.0, 5.0, 5.0);
  } catch (const std::runtime_error&) {
    update_threw = true;
  }
  if (!expect(update_threw,
              "guard: update_sketch_line rejects generated lines")) {
    return false;
  }

  bool trim_threw = false;
  try {
    manager.trim_sketch_entity(glyph_id, 1.0, 1.0);
  } catch (const std::runtime_error&) {
    trim_threw = true;
  }
  if (!expect(trim_threw,
              "guard: trim_sketch_entity rejects generated lines")) {
    return false;
  }

  bool move_threw = false;
  try {
    manager.move_sketch_entities({glyph_id}, 5.0, 0.0, 0.0, 0.0, 0.0);
  } catch (const std::runtime_error&) {
    move_threw = true;
  }
  if (!expect(move_threw,
              "guard: move_sketch_entities rejects generated lines")) {
    return false;
  }

  bool dim_threw = false;
  try {
    manager.add_sketch_line_length_dimension(glyph_id);
  } catch (const std::runtime_error&) {
    dim_threw = true;
  }
  if (!expect(dim_threw,
              "guard: dimensions reject generated lines")) {
    return false;
  }

  bool constraint_threw = false;
  try {
    manager.set_sketch_line_constraint(glyph_id, std::string("horizontal"));
  } catch (const std::runtime_error&) {
    constraint_threw = true;
  }
  return expect(constraint_threw,
                "guard: constraints reject generated lines");
}

bool test_extrude_from_text() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = "O";
  text.height_mm = 20.0;
  DocumentState document = manager.add_sketch_text(text);
  const auto params = sketch_params(document);

  // Extrude only the OUTER ring — the hole profile rides along as an
  // inner loop of the outer region, exactly like a user extruding the
  // pickable outer face (selecting both regions would create two
  // overlapping extrusions instead of one hollow body).
  std::string outer_profile_id;
  for (const auto& profile : params.profiles) {
    if (!profile.inner_loops.empty()) {
      outer_profile_id = profile.id;
    }
  }
  if (!expect(!outer_profile_id.empty(),
              "extrude: outer ring region found")) {
    return false;
  }
  document = manager.extrude_profile(outer_profile_id, /*depth=*/5.0,
                                     /*mode=*/"new_body");

  const auto compiled = compile_bodies(document);
  if (!expect(compiled.bodies.size() == 1,
              "extrude: one compiled body")) {
    return false;
  }

  // The extruded "O" is a ring prism: 4 lateral walls (outer + hole
  // walls, split at glyph corners into many faces — assert ≥ 6) and a
  // hollow interior (volume well below the bounding-box fill).
  TopExp_Explorer face_ex(compiled.bodies.front().shape, TopAbs_FACE);
  int face_count = 0;
  for (; face_ex.More(); face_ex.Next()) ++face_count;
  if (!expect(face_count >= 6,
              "extrude: ring prism has outer + hole walls + caps")) {
    return false;
  }

  GProp_GProps props;
  BRepGProp::VolumeProperties(compiled.bodies.front().shape, props);
  const double volume = props.Mass();
  return expect(volume > 0.0 && volume < 20.0 * 20.0 * 5.0 * 0.5,
                "extrude: positive volume, hollow ring (not a filled box)");
}

bool test_delete_text_via_selection() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = "O";
  text.height_mm = 10.0;
  DocumentState document = manager.add_sketch_text(text);
  const auto params = sketch_params(document);
  const auto generated = generated_line_ids(params);

  // Selecting a glyph segment and deleting removes the owning text
  // entity (Fusion behaviour), not the generated line.
  document = manager.delete_sketch_selection(
      {generated.front()}, /*point_ids=*/{}, /*profile_ids=*/{});
  const auto after = sketch_params(document);
  if (!expect(after.texts.empty(), "delete: text entity removed")) {
    return false;
  }
  if (!expect(generated_line_ids(after).empty(),
              "delete: generated glyph lines removed")) {
    return false;
  }
  return expect(after.profiles.empty(), "delete: text profiles removed");
}

const polysmith::core::FeatureEntry* find_extrude(
    const DocumentState& document) {
  const auto it = std::find_if(
      document.feature_history.begin(), document.feature_history.end(),
      [](const auto& feature) { return feature.kind == "extrude"; });
  return it == document.feature_history.end() ? nullptr : &*it;
}

bool test_save_load_round_trip() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = "OK";
  text.height_mm = 12.0;
  text.angle_deg = 15.0;
  text.h_align = "left";
  text.v_align = "top";
  text.char_spacing = 0.25;
  DocumentState document = manager.add_sketch_text(text);
  const auto before = sketch_params(document);

  const std::string path =
      (std::filesystem::temp_directory_path() / "polysmith_text_test.polysmith")
          .string();
  manager.save_document_to_path(path);

  DocumentManager loaded_manager;
  loaded_manager.create_document();
  DocumentState loaded = loaded_manager.load_document_from_path(path);
  const auto after = sketch_params(loaded);

  if (!expect(after.texts.size() == 1,
              "round-trip: text record survives")) {
    return false;
  }
  const auto& entry = after.texts[0];
  if (!expect(entry.id == before.texts[0].id &&
                  entry.text == before.texts[0].text &&
                  entry.height_mm == before.texts[0].height_mm &&
                  entry.angle_deg == before.texts[0].angle_deg &&
                  entry.h_align == before.texts[0].h_align &&
                  entry.v_align == before.texts[0].v_align &&
                  entry.char_spacing == before.texts[0].char_spacing,
              "round-trip: text parameters identical")) {
    return false;
  }

  // Deterministic re-expansion: the reloaded document's first refresh
  // reproduces the exact same generated lines (zero save/load churn).
  if (!expect(after.lines.size() == before.lines.size(),
              "round-trip: generated segment count identical")) {
    return false;
  }
  for (size_t i = 0; i < before.lines.size(); ++i) {
    if (!expect(after.lines[i].id == before.lines[i].id &&
                    std::abs(after.lines[i].start_x - before.lines[i].start_x) <
                        1e-9 &&
                    std::abs(after.lines[i].end_y - before.lines[i].end_y) <
                        1e-9,
                "round-trip: generated ids + coords identical")) {
      return false;
    }
  }
  for (const auto& profile : before.profiles) {
    const auto found = std::find_if(
        after.profiles.begin(), after.profiles.end(),
        [&](const auto& p) { return p.id == profile.id; });
    if (!expect(found != after.profiles.end(),
                "round-trip: profile ids identical")) {
      return false;
    }
  }
  return true;
}

bool test_tnp_break_vs_survive_matrix() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = "O";
  text.height_mm = 20.0;
  DocumentState document = manager.add_sketch_text(text);
  auto params = sketch_params(document);

  // Extrude only the outer ring (the hole is an inner loop).
  std::string outer_profile_id;
  for (const auto& profile : params.profiles) {
    if (!profile.inner_loops.empty()) {
      outer_profile_id = profile.id;
    }
  }
  if (!expect(!outer_profile_id.empty(),
              "tnp: outer ring region found")) {
    return false;
  }
  document = manager.extrude_profile(outer_profile_id, /*depth=*/5.0,
                                     /*mode=*/"new_body");
  const auto* extrude = find_extrude(document);
  if (!expect(extrude != nullptr && !extrude->dependency_broken,
              "tnp: extrude starts healthy")) {
    return false;
  }

  // The extrude deactivates the sketch (Fusion-style: extruding exits
  // the sketch edit). Re-enter it before editing the text, exactly as
  // the UI does when the user double-clicks the sketch in the timeline.
  const auto& text_sketch = document.feature_history[1];
  document = manager.reenter_sketch(text_sketch.id);

  // Height-only edit: the generated id set is unchanged (proportional
  // tessellation tolerance), so the extrude re-snapshots and stays
  // healthy.
  params = sketch_params(document);
  SketchText updated = params.texts[0];
  updated.height_mm = 30.0;
  document = manager.update_sketch_text(updated.id, updated);
  extrude = find_extrude(document);
  if (!expect(extrude != nullptr && !extrude->dependency_broken,
              "tnp: height edit keeps the extrude healthy")) {
    return false;
  }

  // String edit: the generated id set changes, the old profile can no
  // longer be re-identified, and the extrude degrades through the
  // existing dependency_broken path (no crash, timeline warning).
  params = sketch_params(document);
  updated = params.texts[0];
  updated.text = "AB";
  document = manager.update_sketch_text(updated.id, updated);
  extrude = find_extrude(document);
  return expect(extrude != nullptr && extrude->dependency_broken &&
                    !extrude->dependency_warning.empty(),
                "tnp: string edit degrades the extrude with a warning");
}

// Regression for the dual tool-whitelist bug: the document-layer
// `is_supported_sketch_tool` check ran before the sketch-layer
// `validate_tool` and lacked "text", so clicking the Text tool threw
// "Unsupported sketch tool: text" even though the core supported it.
bool test_set_text_tool_accepted() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");
  const DocumentState document = manager.set_sketch_tool("text");
  return expect(document.active_sketch_tool.has_value() &&
                    document.active_sketch_tool.value() == "text",
                "text tool accepted by the sketch session");
}

// Glyph corners are derived geometry: the viewport must not emit point
// spheres or FIX constraint badges for them (a badge per glyph corner
// drowns the sketch in markers — the reported clutter bug).
bool test_no_glyph_vertex_markers() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = "OK";
  text.height_mm = 10.0;
  const DocumentState document = manager.add_sketch_text(text);
  const auto viewport =
      polysmith::core::build_viewport_state(std::optional<DocumentState>(document));

  for (const auto& vertex : viewport.sketch_vertices) {
    if (!expect(vertex.vertex_id.rfind("vertex-text-", 0) != 0,
                "viewport: glyph corners emit no point primitives")) {
      return false;
    }
  }
  for (const auto& constraint : viewport.sketch_constraints) {
    if (!expect(!(constraint.kind == "fixed" &&
                  constraint.entity_id.rfind("vertex-text-", 0) == 0),
                "viewport: glyph corners emit no FIX badges")) {
      return false;
    }
  }
  // Sanity: the glyph lines themselves ARE visible to the renderer.
  bool saw_glyph_line = false;
  for (const auto& line : viewport.sketch_lines) {
    if (line.generated_by.has_value()) {
      saw_glyph_line = true;
    }
  }
  return expect(saw_glyph_line,
                "viewport: glyph lines still render");
}

// Fusion-style text on path: the text record references a sketch line
// or arc; the expansion places every glyph on that curve, rotated to
// its tangent.
bool test_text_on_line_path() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  DocumentState document = manager.add_sketch_line(0.0, 0.0, 100.0, 0.0);
  auto params = sketch_params(document);
  const std::string path_id = params.lines.back().id;

  SketchText text;
  text.text = "OK";
  text.height_mm = 10.0;
  text.path_entity_id = path_id;
  document = manager.add_sketch_text(text);
  params = sketch_params(document);

  if (!expect(!generated_line_ids(params).empty(),
              "line path: glyph geometry generated")) {
    return false;
  }
  // Every glyph vertex rides the horizontal path at y ≈ 0 (glyph
  // outline points extend within cap-height of the baseline).
  for (const auto& line : params.lines) {
    if (!line.generated_by.has_value()) continue;
    if (!expect(std::abs(line.start_y) < 15.0 &&
                    std::abs(line.end_y) < 15.0 &&
                    line.start_x >= -1.0 && line.end_x <= 101.0,
                "line path: glyph vertices hug the path line")) {
      return false;
    }
  }

  // Glyphs still form complete closed profile regions.
  const int expected = expected_contour_count("OK", 10.0);
  if (!expect(expected > 0 && static_cast<int>(params.profiles.size()) ==
                                  expected,
              "line path: one profile region per glyph contour")) {
    return false;
  }
  std::vector<polysmith::test::ExpectedProfile> expected_profiles;
  for (const auto& profile : params.profiles) {
    expected_profiles.push_back({.entity_ids = profile.line_ids,
                                 .kind = "polygon",
                                 .has_source_circle_id = false});
  }
  std::string reason;
  return expect(
      polysmith::test::profiles_match(document, expected_profiles, &reason),
      ("line path: complete region set: " + reason).c_str());
}

bool test_text_on_arc_path() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  // Quarter arc centered at (0,0), radius 40, from (40,0) to (0,40).
  DocumentState document = manager.add_sketch_arc(
      40.0, 0.0, 0.0, 40.0, 0.0, 0.0, "center_start_end");
  auto params = sketch_params(document);
  const std::string path_id = params.arcs.back().id;

  SketchText text;
  text.text = "OK";
  text.height_mm = 10.0;
  text.path_entity_id = path_id;
  document = manager.add_sketch_text(text);
  params = sketch_params(document);

  if (!expect(!generated_line_ids(params).empty(),
              "arc path: glyph geometry generated")) {
    return false;
  }
  // Glyph vertices stay within glyph-extent of the circle radius.
  for (const auto& line : params.lines) {
    if (!line.generated_by.has_value()) continue;
    const auto check_radius = [&](double x, double y) {
      const double radius = std::sqrt(x * x + y * y);
      return expect(radius > 25.0 && radius < 60.0,
                    "arc path: glyph vertices hug the circle");
    };
    if (!check_radius(line.start_x, line.start_y) ||
        !check_radius(line.end_x, line.end_y)) {
      return false;
    }
  }

  const int expected = expected_contour_count("OK", 10.0);
  return expect(expected > 0 && static_cast<int>(params.profiles.size()) ==
                                    expected,
                "arc path: one profile region per glyph contour");
}

bool test_text_path_bind_and_recover() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  DocumentState document = manager.add_sketch_line(0.0, 0.0, 100.0, 0.0);
  auto params = sketch_params(document);
  const std::string path_id = params.lines.back().id;

  // Missing path degrades gracefully (render_error, no geometry, no
  // crash) and recovers once a real path is bound.
  SketchText text;
  text.text = "OK";
  text.height_mm = 10.0;
  text.path_entity_id = std::string("line-999");
  document = manager.add_sketch_text(text);
  params = sketch_params(document);
  if (!expect(params.texts.size() == 1 &&
                  !params.texts[0].render_error.empty() &&
                  generated_line_ids(params).empty(),
              "bind: missing path sets render_error and emits nothing")) {
    return false;
  }

  SketchText updated = params.texts[0];
  updated.path_entity_id = path_id;
  document = manager.update_sketch_text(updated.id, updated);
  params = sketch_params(document);
  if (!expect(!generated_line_ids(params).empty(),
              "bind: real path generates geometry")) {
    return false;
  }
  if (!expect(params.texts[0].render_error.empty(),
              "bind: render_error cleared after recovery")) {
    return false;
  }

  // Clearing the path returns the text to flat layout (anchor at the
  // stored anchor point).
  updated = params.texts[0];
  updated.path_entity_id = std::nullopt;
  document = manager.update_sketch_text(updated.id, updated);
  params = sketch_params(document);
  return expect(!generated_line_ids(params).empty() &&
                    !params.texts[0].path_entity_id.has_value(),
                "bind: clearing the path falls back to flat text");
}

bool test_multiline_profiles() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = "AB\nCD";
  text.height_mm = 10.0;
  DocumentState document = manager.add_sketch_text(text);
  const auto params = sketch_params(document);

  // Every glyph contour on every line becomes exactly one region.
  const int expected = expected_contour_count("AB\nCD", 10.0);
  if (!expect(expected > 0 &&
                  static_cast<int>(params.profiles.size()) == expected,
              "multiline: one profile region per glyph contour")) {
    return false;
  }
  std::vector<polysmith::test::ExpectedProfile> expected_profiles;
  for (const auto& profile : params.profiles) {
    expected_profiles.push_back({.entity_ids = profile.line_ids,
                                 .kind = "polygon",
                                 .has_source_circle_id = false});
  }
  std::string reason;
  return expect(
      polysmith::test::profiles_match(document, expected_profiles, &reason),
      ("multiline: complete region set: " + reason).c_str());
}

bool test_degenerate_strings() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  // Empty and whitespace-only strings render no geometry — the text
  // record persists so the user can type into it, and nothing crashes.
  SketchText text;
  text.text = "   ";
  DocumentState document = manager.add_sketch_text(text);
  auto params = sketch_params(document);
  if (!expect(params.texts.size() == 1 &&
                  generated_line_ids(params).empty(),
              "degenerate: whitespace-only text generates no geometry")) {
    return false;
  }
  if (!expect(params.profiles.empty(),
              "degenerate: no profiles from empty glyphs")) {
    return false;
  }

  SketchText updated = params.texts[0];
  updated.text = "OK";
  document = manager.update_sketch_text(updated.id, updated);
  params = sketch_params(document);
  return expect(!generated_line_ids(params).empty(),
                "degenerate: typing real text after empty string works");
}

bool test_char_limit() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = std::string(501, 'X');
  bool threw = false;
  try {
    manager.add_sketch_text(text);
  } catch (const std::runtime_error&) {
    threw = true;
  }
  if (!expect(threw, "cap: 501 characters is rejected")) {
    return false;
  }

  // The failed add must not leave a half-created text or geometry.
  const auto params = sketch_params(manager.get_document().value());
  return expect(params.texts.empty() && generated_line_ids(params).empty(),
                "cap: rejected add leaves the sketch untouched");
}

bool test_undo_restores_text() {
  DocumentManager manager;
  manager.create_document();
  manager.start_sketch_on_plane("ref-plane-xy");

  SketchText text;
  text.text = "O";
  text.height_mm = 10.0;
  DocumentState document = manager.add_sketch_text(text);
  const auto with_text = sketch_params(document);

  document = manager.undo();
  const auto undone = sketch_params(document);
  if (!expect(undone.texts.empty() && generated_line_ids(undone).empty(),
              "undo: text and glyph lines gone")) {
    return false;
  }

  document = manager.redo();
  const auto redone = sketch_params(document);
  if (!expect(redone.texts.size() == 1 &&
                  redone.lines.size() == with_text.lines.size(),
              "redo: text and glyph lines restored")) {
    return false;
  }
  return expect(redone.texts[0].id == with_text.texts[0].id &&
                    redone.lines[0].id == with_text.lines[0].id,
                "redo: ids restored exactly");
}

}  // namespace

#define RUN_TEST(name)                        \
  do {                                        \
    std::cerr << "--- " << #name << "\n";     \
    if (!(name)()) return 1;                  \
  } while (0)

int main() {
  RUN_TEST(test_text_o_profiles);
  RUN_TEST(test_text_ab_profiles);
  RUN_TEST(test_reexpansion_stability);
  RUN_TEST(test_height_edit_keeps_ids_and_scales);
  RUN_TEST(test_string_edit_changes_ids);
  RUN_TEST(test_guards_reject_generated_entities);
  RUN_TEST(test_extrude_from_text);
  RUN_TEST(test_delete_text_via_selection);
  RUN_TEST(test_save_load_round_trip);
  RUN_TEST(test_tnp_break_vs_survive_matrix);
  RUN_TEST(test_undo_restores_text);
  RUN_TEST(test_multiline_profiles);
  RUN_TEST(test_degenerate_strings);
  RUN_TEST(test_char_limit);
  RUN_TEST(test_set_text_tool_accepted);
  RUN_TEST(test_no_glyph_vertex_markers);
  RUN_TEST(test_text_on_line_path);
  RUN_TEST(test_text_on_arc_path);
  RUN_TEST(test_text_path_bind_and_recover);

  std::cout << "text_test passed\n";
  return 0;
}
