#include "core/sketch/constraint_solver.h"
#include "core/sketch/impl/private_vertex_lookup_helpers.inc"

#include <Constraints.h>
#include <GCS.h>
#include <Geo.h>
#include <algorithm>
#include <cmath>
#include <set>
#include <stdexcept>

namespace polysmith::core {

namespace {

// Arcs regenerated by enforcement passes (fillets, projections, text/slot
// expansion) are excluded from the solver: their geometry is re-derived
// from their sources after every solve, so registering them would create
// redundant/conflicting constraints (e.g. projected arcs have fixed
// endpoints, over-constraining their circle).
bool is_derived_arc(const SketchFeatureParameters& params,
                    const SketchArc& arc) {
  if (arc.generated_by.has_value()) return true;
  for (const auto& fillet : params.fillets) {
    if (fillet.arc_id == arc.id) return true;
  }
  for (const auto& projection : params.projections) {
    for (const auto& generated_id : projection.generated_arc_ids) {
      if (generated_id == arc.id) return true;
    }
  }
  return false;
}

// An arc is registered in the solver ONLY when a solver constraint
// actually references it.  Dimension drives on arcs (arc_radius /
// arc_angle) are handled by the deterministic enforcement pass
// (enforce_arc_dimensions) instead of the solver: planegcs wanders the
// null space of an unanchored arc (free translation + rotation + sweep)
// even from a zero-residual reference, drifting the arc on every solve.
// Unregistered arcs have their vertices pinned during solves (see
// constraint_solver_system_setup.inc), so a lone arc can never drift.
bool arc_participates_in_solver(const SketchFeatureParameters& params,
                                const SketchArc& arc) {
  for (const auto& rel : params.line_relations) {
    if (rel.kind == "tangent_line_arc" && rel.second_line_id == arc.id) {
      return true;
    }
  }
  for (const auto& constraint : params.constraints) {
    if (constraint.kind == "tangent_arc_arc") {
      for (const auto& target_id : constraint.target_ids) {
        if (target_id == arc.id) return true;
      }
    }
  }
  return false;
}

}  // namespace

void ConstraintSolver::build(const SketchFeatureParameters& params) {
#include "core/sketch/impl/constraint_solver_parameter_storage.inc"
#include "core/sketch/impl/constraint_solver_entity_mapping.inc"
#include "core/sketch/impl/constraint_solver_system_setup.inc"
#include "core/sketch/impl/constraint_solver_geometric_constraints.inc"
#include "core/sketch/impl/constraint_solver_dimension_constraints.inc"
}

#include "core/sketch/impl/constraint_solver_lifecycle.inc"

}  // namespace polysmith::core
