#pragma once

#include <string>

namespace polysmith::core {

// 2D parametric corner chamfer on the sketch plane. Replaces a corner
// formed by two intersecting `SketchLine`s with a straight chamfer
// line, trimming each line back by its own distance (symmetric when
// distance_a == distance_b). The chamfer is parametric: lines A and B
// store their *trim* endpoint (not the original corner) and the chamfer
// line's two endpoints, but `corner_vertex_id` is preserved so the
// relationship can be re-solved on every recompute (when one of the
// lines moves) and fully reverted on delete — the same lifecycle as
// SketchFillet, with a line instead of an arc.
//
// Lifecycle:
//   - Create: `add_sketch_chamfer(corner, line_a, line_b, distance_a,
//     distance_b)` allocates the two trim points + the chamfer line,
//     mutates lines A and B to swap `corner_vertex_id` for the new
//     trim point ids, and appends a SketchChamfer record.
//   - Recompute: every `refresh_sketch_derived_state` runs
//     `enforce_sketch_chamfers`, which re-derives the trim positions
//     from the current line endpoints and the stored distances.
//   - Edit: `update_sketch_chamfer` rewrites the distances and
//     re-runs the recompute pass (fit validation deferred, like the
//     fillet radius edit).
//   - Delete: `delete_sketch_chamfer` restores each line's trimmed
//     endpoint back to `corner_vertex_id`, removes the chamfer line +
//     trim points + the record itself.
//
// v1 limitation: only line-line chamfers (no line-arc, arc-arc).
// A corner holding both a fillet and a chamfer is rejected.
struct SketchChamfer {
  std::string id;
  // The pre-chamfer shared corner, kept alive in `parameters.vertices`
  // by `rebuild_sketch_vertices` (mirrors the fillet's corner cache).
  std::string corner_vertex_id;
  // Cached corner coords, updated by `enforce_sketch_chamfers` on
  // every recompute.
  double corner_x;
  double corner_y;
  std::string line_a_id;
  std::string line_b_id;
  // Generated geometry — owned by the chamfer record, regenerated by
  // the recompute pass on every sketch edit.
  std::string trim_a_vertex_id;
  std::string trim_b_vertex_id;
  std::string chamfer_line_id;
  // Trim distance from the corner along each line. Both must be
  // positive and fit within their line.
  double distance_a;
  double distance_b;
};

}  // namespace polysmith::core
