#pragma once

#include <optional>
#include <string>
#include <vector>

namespace polysmith::core {

struct SketchProfilePoint {
  double x;
  double y;
};

struct SketchLine {
  std::string id;
  // ── Vertex unification ──────────────────────────────────────
  // Stable "vertex-N" identifiers. These are the canonical endpoint IDs.
  std::string start_vertex_id;
  std::string end_vertex_id;
  double start_x;
  double start_y;
  double end_x;
  double end_y;
  std::optional<std::string> constraint;
  // When true, the H/V constraint on this line is a reference (driven)
  // constraint. The solver ignores it; the UI renders it in parentheses.
  bool constraint_driven = false;
  // True when the line is a "construction" line (contextual modeling
  // dashed reference geometry). Construction lines participate in
  // snapping and constraints, but are excluded from profile loop
  // detection so they don't seal profiles for face picking / extrude
  // sources. Defaults to false; older saves are loaded as solid.
  bool is_construction = false;
  // When set, the line is derived geometry generated by a parametric
  // source (currently the sketch text expansion: "text:<text-id>").
  // Generated entities are not user-editable — guards reject edit /
  // trim / move / dimension / constraint commands that target them,
  // and the expansion pass strips + regenerates them on every recompute.
  std::optional<std::string> generated_by;
};

struct SketchCircle {
  std::string id;
  // ── Vertex unification (Phase 5) ────────────────────────────
  std::string center_vertex_id;
  double center_x;
  double center_y;
  double radius;
  bool is_construction = false;
  // See SketchLine::generated_by (reserved — the v1 text expansion only
  // emits lines).
  std::optional<std::string> generated_by;
};

// Regular polygon on the sketch plane. Supports three creation modes:
//   "circumscribed" — polygon circumscribed around a circle (center+radius).
//   "inscribed"     — polygon inscribed in a circle (center+radius).
//   "edge"          — polygon defined by one edge (two points).
struct SketchPolygon {
  std::string id;
  double center_x;
  double center_y;
  double radius;
  int sides;          // >= 3
  std::string mode;   // "circumscribed" | "inscribed" | "edge"
  double start_x;
  double start_y;
  double end_x;
  double end_y;
  bool is_construction = false;
};

// 2D arc on the sketch plane. Stored as start/end endpoint ids (so it
// participates in the shared point graph just like a SketchLine) plus
// a fully-cached (center, radius, ccw) triple. v1 freezes the arc's
// shape at creation: the endpoint points are flagged is_fixed=true so
// the user can't drag them off the cached arc, and there is no
// constraint / dimension support on arcs yet. Editing flows on arcs
// (drag-to-reshape, radius dimension, etc.) are deliberately left
// for a follow-up so the loop / extrude integration here doesn't have
// to worry about the cached params drifting from the endpoints.
struct SketchArc {
  std::string id;
  // ── Vertex unification ──────────────────────────────────────
  // Stable "vertex-N" identifiers. These are the canonical endpoint IDs.
  std::string start_vertex_id;
  std::string end_vertex_id;
  std::string center_vertex_id;
  // Cached shape parameters. Endpoint coordinates duplicate the
  // owning SketchVertex coordinates, mirroring how SketchLine caches
  // its endpoints, so consumers (renderer, profile builder) don't
  // have to chase pointer references for every paint.
  double center_x;
  double center_y;
  double radius;
  double start_x;
  double start_y;
  double end_x;
  double end_y;
  // True when the sweep from start to end runs counter-clockwise in
  // sketch-plane coordinates. Combined with the cached endpoints this
  // disambiguates which side of the chord the arc bulges to (a major
  // vs minor arc).
  bool ccw;
  bool is_construction = false;
  // See SketchLine::generated_by (reserved — the v1 text expansion only
  // emits lines).
  std::optional<std::string> generated_by;
};

// Full ellipse entity (feature/sketch milestone).  v1 creates it
// center + major-axis point + minor-axis point; the axis points are
// flagged fixed at creation so the cached shape never drifts (the
// solver has no ellipse registration yet — FreeCAD's ellipse solving
// is historically fragile, so parametric ellipses are a follow-up).
struct SketchEllipse {
  std::string id;
  std::string center_vertex_id;
  std::string axis_a_vertex_id;  // major-axis direction point
  std::string axis_b_vertex_id;  // minor-axis direction point
  // Cached shape parameters (mirrors SketchCircle's caching pattern).
  double center_x;
  double center_y;
  double a;           // major radius
  double b;           // minor radius
  double rotation;    // major-axis angle in sketch-plane coordinates
  bool is_construction = false;
  std::optional<std::string> generated_by;
  // Partial ellipse (a trim result). has_sweep=false means the full
  // closed ellipse (creation and all pre-trim saves).  Angles are
  // ellipse-frame parametric angles (radians) — the same convention
  // exact_curve_point uses for kEllipse.
  bool has_sweep = false;
  double sweep_start_angle = 0.0;
  double sweep_end_angle = 0.0;
  bool ccw = true;
  std::string start_vertex_id;  // minted/shared split vertices (partial only)
  std::string end_vertex_id;
};

// Control-point B-spline entity (feature/sketch). v1: the user's
// clicks ARE the control poles — regular movable vertices. The drawn
// curve is the clamped degree-3 B-spline they define (see
// spline_math.h for the shared evaluation). No solver registration
// (FreeCAD's BSpline solving is a regression factory) — pole drags
// re-fit the cached curve through the ordinary vertex sync passes.
struct SketchSpline {
  std::string id;
  // One vertex per pole, in order.  Regular "vertex-N" vertices so
  // pole dragging works through the existing vertex paths.
  std::vector<std::string> pole_vertex_ids;
  // Cached pole coordinates (sketch-local), re-synced from the vertex
  // table on every refresh — vertices are the single source of truth.
  std::vector<double> pole_xs;
  std::vector<double> pole_ys;
  int degree = 3;  // min(3, pole_count - 1); clamped open-uniform knots
  bool is_construction = false;
  std::optional<std::string> generated_by;
};

struct SketchVertex {
  std::string id;
  // ── Vertex unification (Phase 4) ────────────────────────────
  // Stable "vertex-N" identifier assigned by rebuild_sketch_vertices.
  // This will become the primary point identifier in Phase 6.
  std::string vertex_id;
  std::string kind;
  double x;
  double y;
  bool is_fixed;

  // ── Vertex unification fields (Phase 1) ─────────────────────
  // IDs of the geometry entities (lines, circles, arcs) that own
  // this vertex.  For a line endpoint this is [line_id]; for a
  // shared corner it is [line_a_id, line_b_id].  Populated in
  // Phase 2.
  std::vector<std::string> geometry_owner_ids;

  // True when this point was produced by the Project tool from
  // 3D body geometry.
  bool is_projected = false;

  // Source of the projection (only meaningful when is_projected).
  // e.g. "edge_midpoint", "vertex", "face_center"
  std::optional<std::string> source_type;
  // Feature id of the body the projection came from.
  std::optional<std::string> source_feature_id;
  // Edge id if the source was an edge midpoint / endpoint.
  std::optional<std::string> source_edge_id;
};

// Standalone sketch point produced by the Project tool when the user
// projects a body vertex onto the active sketch plane. Unlike line /
// arc / circle endpoints, projected points are not derived from any
// other sketch entity — they have to be re-emitted by
// `rebuild_sketch_vertices` from this list directly. The cached (x, y)
// is the projected location in sketch-local coordinates; `source_id`
// records the body vertex id (`<body>:vertex:<index>`) so the
// projection is idempotent (clicking the same vertex twice is a
// no-op) and can be located by future edits.
struct SketchProjectedPoint {
  std::string id;
  std::string source_id;
  double x;
  double y;
};

}  // namespace polysmith::core
