#pragma once

#include <string>

namespace polysmith::core {

// 2D parametric corner fillet on the sketch plane. Replaces a corner
// formed by two intersecting `SketchLine`s with a tangent
// `SketchArc`, trimming each line back to its tangent point. The
// fillet is parametric: lines A and B store their *trim* endpoint
// (not the original corner) and the arc's two endpoints, but the
// `corner_vertex_id` is preserved so the relationship can be
// re-solved on every recompute (when one of the lines moves) and
// fully reverted on `delete_sketch_fillet`.
//
// Lifecycle:
//   - Create: `add_sketch_fillet(corner, line_a, line_b, radius)`
//     allocates the two trim points + the arc, mutates lines A and
//     B to swap `corner_vertex_id` for the new trim point ids, and
//     appends a SketchFillet record.
//   - Recompute: every `refresh_sketch_derived_state` runs
//     `enforce_sketch_fillets`, which re-derives the trim positions
//     and arc parameters from the current line endpoints. This
//     keeps the fillet tangent when the user drags the line on the
//     opposite end ("far" endpoint) of either filleted line.
//   - Edit radius: `update_sketch_fillet_radius` rewrites `radius`
//     and re-runs the recompute pass.
//   - Delete: `delete_sketch_fillet` restores each line's filleted
//     endpoint back to `corner_vertex_id`, removes the arc + trim
//     points + the record itself, leaving the original corner
//     intact.
//
// v1 limitation: only line-line fillets (no line-arc, arc-arc).
struct SketchFillet {
  std::string id;
  // The pre-fillet shared corner. The fillet keeps this point alive
  // in `parameters.vertices` (re-emitted by `rebuild_sketch_vertices`)
  // even when no other line / arc still references it, because
  // delete needs to restore it as the lines' shared endpoint.
  std::string corner_vertex_id;
  // Cached corner coords, updated by `enforce_sketch_fillets` on
  // every recompute. Without these the point would have nowhere to
  // pull its coords from once both filleted lines have been
  // mutated to reference the trim points instead.
  double corner_x;
  double corner_y;
  std::string line_a_id;
  std::string line_b_id;
  // Generated geometry — owned by the fillet, regenerated by the
  // recompute pass on every sketch edit.
  std::string trim_a_vertex_id;
  std::string trim_b_vertex_id;
  std::string arc_id;
  double radius;
};

}  // namespace polysmith::core
