import type { ConstraintType } from "@/types";

export interface SceneBounds {
  center: [number, number, number];
  size: [number, number, number];
  maxDimension: number;
}

export interface BoxScenePrimitive {
  kind: "box";
  primitiveId: string;
  label: string;
  size: [number, number, number];
  position: [number, number, number];
  isSelected: boolean;
  appearanceColor: string | null;
}

export interface CylinderScenePrimitive {
  kind: "cylinder";
  primitiveId: string;
  label: string;
  radius: number;
  height: number;
  position: [number, number, number];
  planeId: string;
  planeFrame: {
    origin: [number, number, number];
    xAxis: [number, number, number];
    yAxis: [number, number, number];
    normal: [number, number, number];
  } | null;
  isSelected: boolean;
  appearanceColor: string | null;
}

export interface PolygonExtrudeScenePrimitive {
  kind: "polygon_extrude";
  primitiveId: string;
  label: string;
  planeId: string;
  planeFrame: {
    origin: [number, number, number];
    xAxis: [number, number, number];
    yAxis: [number, number, number];
    normal: [number, number, number];
  } | null;
  profilePoints: [number, number][];
  innerLoops: [number, number][][];
  depth: number;
  isSelected: boolean;
  appearanceColor: string | null;
}

// World-space polyline for a body edge; the renderer turns this into a
// THREE.Line and raycasts against it for picking.
export interface SceneEdge {
  edgeId: string;
  ownerBodyId: string;
  kind: "line" | "circle" | "curve";
  points: Float32Array;
  isSelected: boolean;
  // True when this edge belongs to a body that has a pending fillet /
  // chamfer feature in the document. Ghost edges stay fully pickable
  // (so the user can add / remove edges from the in-progress
  // operation), but the viewport hides them by default to keep the
  // post-op preview visually clean. Tab toggles them visible.
  isGhost: boolean;
}

// World-space vertex of a body. The renderer materializes these as
// small THREE.Points / sphere meshes and raycasts against them ahead
// of edges so vertices are reliably grabbable.
export interface SceneVertex {
  vertexId: string;
  ownerBodyId: string;
  position: [number, number, number];
  isSelected: boolean;
}

export interface MeshScenePrimitive {
  kind: "mesh";
  primitiveId: string;
  label: string;
  // Flat triangle list ready for THREE.BufferGeometry, in world space.
  positions: Float32Array;
  normals: Float32Array;
  indices: Uint32Array;
  isSelected: boolean;
  appearanceColor: string | null;
}

// Translucent red overlay rendered on top of the booleaned body while
// the user is editing a cut extrude. Mirrors the contextual modeling "you're
// about to remove this volume" feedback. The renderer keeps the
// material non-pickable (the user picks the booleaned body's faces,
// not this overlay).
export interface CutPreviewScene {
  id: string;
  positions: Float32Array;
  normals: Float32Array;
  indices: Uint32Array;
}

export type ScenePrimitive =
  | BoxScenePrimitive
  | CylinderScenePrimitive
  | PolygonExtrudeScenePrimitive
  | MeshScenePrimitive;

export interface ReferencePlaneScene {
  kind: "reference_plane";
  referenceId: string;
  label: string;
  // Origin planes use the three legacy orientations; construction
  // planes use "custom" and rely on `planeFrame` for placement.
  orientation: "xy" | "yz" | "xz" | "custom";
  position: [number, number, number];
  size: [number, number];
  isSelected: boolean;
  isActiveSketchPlane: boolean;
  // World-space frame for construction planes. Null for origin
  // planes (the renderer uses the legacy orientation rotation
  // instead).
  planeFrame: {
    origin: [number, number, number];
    xAxis: [number, number, number];
    yAxis: [number, number, number];
    normal: [number, number, number];
  } | null;
}

export interface ReferenceAxisScene {
  kind: "reference_axis";
  referenceId: string;
  label: string;
  axis: "x" | "y" | "z" | "custom";
  start: [number, number, number];
  end: [number, number, number];
}

export interface ReferencePointScene {
  kind: "reference_point";
  referenceId: string;
  label: string;
  position: [number, number, number];
  isSelected: boolean;
}

export interface ReferenceHelixScene {
  kind: "reference_helix";
  referenceId: string;
  label: string;
  points: Float32Array;
  isSelected: boolean;
}

export type SceneReference =
  | ReferencePlaneScene
  | ReferenceAxisScene
  | ReferencePointScene
  | ReferenceHelixScene;

export interface SketchLineScene {
  // True when this line is a transient preview generated by a
  // tool (Mirror, Pattern, etc.). Renders dashed and translucent;
  // not selectable.
  isPreview: boolean;
  lineId: string;
  startPointId: string;
  endPointId: string;
  planeId: string;
  start: [number, number, number];
  end: [number, number, number];
  isSelected: boolean;
  constraint: ConstraintType | null;
  // Reference-only construction lines render dashed and don't
  // contribute to profile loop detection in the core.
  isConstruction: boolean;
  isProjected: boolean;
  // Set for glyph segments expanded from a sketch text entry
  // ("text:<text-id>"). Null for hand-drawn / projected lines.
  generatedBy: string | null;
}

export interface SketchEntityPlaneFrame {
  origin: { x: number; y: number; z: number };
  x_axis: { x: number; y: number; z: number };
  y_axis: { x: number; y: number; z: number };
  normal: { x: number; y: number; z: number };
}

export interface SketchCircleScene {
  // See `SketchLineScene.isPreview`.
  isPreview: boolean;
  circleId: string;
  planeId: string;
  planeFrame: SketchEntityPlaneFrame | null;
  center: [number, number, number];
  radius: number;
  isSelected: boolean;
  isConstruction: boolean;
  isProjected: boolean;
  // See `SketchLineScene.generatedBy` (reserved — the v1 text
  // expansion only emits lines).
  generatedBy: string | null;
}

// Ellipse derived from `ViewportSketchEllipse`. The renderer samples
// the perimeter in sketch-plane space (a/b around the rotated major
// axis) and projects each sample through the plane basis — same
// pattern as `SketchCircleScene`. v1 ellipses are fixed-parameter at
// creation, so there is no per-vertex drag on the perimeter.
export interface SketchEllipseScene {
  // See `SketchLineScene.isPreview`.
  isPreview: boolean;
  ellipseId: string;
  planeId: string;
  planeFrame: SketchEntityPlaneFrame | null;
  center: [number, number, number];
  a: number;
  b: number;
  rotation: number;
  isSelected: boolean;
  isConstruction: boolean;
  // See `SketchLineScene.generatedBy` (reserved — v1 ellipses are
  // user entities only).
  generatedBy: string | null;
}

// Regular polygon derived from ViewportSketchPolygon.
export interface SketchPolygonScene {
  isPreview: boolean;
  polygonId: string;
  planeId: string;
  corners: number[];
  isSelected: boolean;
  isConstruction: boolean;
}

// 2D arc derived from `ViewportSketchArc`. The renderer turns this
// into a THREE.Line by sampling the arc between `start` and `end`
// around `center` along the stored sweep direction. v1 freezes the
// arc's shape at creation, so endpoint drag is disabled at the
// THREE picking layer; consumers still treat start/end as snap
// targets via the shared SketchPoint graph.
export interface SketchArcScene {
  // See `SketchLineScene.isPreview`.
  isPreview: boolean;
  arcId: string;
  startPointId: string;
  endPointId: string;
  planeId: string;
  planeFrame: SketchEntityPlaneFrame | null;
  center: [number, number, number];
  radius: number;
  start: [number, number, number];
  end: [number, number, number];
  ccw: boolean;
  isSelected: boolean;
  isConstruction: boolean;
  isProjected: boolean;
  // See `SketchLineScene.generatedBy` (reserved — the v1 text
  // expansion only emits lines).
  generatedBy: string | null;
}

export interface SketchVertexScene {
  // "endpoint" — line / arc endpoint (default).
  // "center" — circle center.
  // "projected" — standalone point placed by the Project tool. The
  // renderer draws these with a small distinguishing crosshair so
  // the user can tell derived geometry from sketched geometry at a
  // glance.
  // "quadrant" — derived cardinal point on a circle perimeter.
  // "fillet_corner" — internal fillet bookkeeping vertex, filtered from scene.
  /** vertex-N ID from Phase 4 vertex unification (canonical). */
  id: string;
  kind: "endpoint" | "center" | "projected" | "quadrant" | "fillet_corner";
  position: [number, number, number];
  isFixed: boolean;
  isSelected: boolean;
  // ── Vertex unification (Phase 1) ───────────────────────────
  geometryOwnerIds?: string[];
  isProjected?: boolean;
  sourceType?: string;
  sourceFeatureId?: string;
  sourceEdgeId?: string;
}

export interface SketchDimensionScene {
  dimensionId: string;
  planeId: string;
  kind:
    | "line_length"
    | "circle_radius"
    | "arc_radius"
    | "polygon_radius"
    | "angle"
    | "line_angle"
    | "line_line_distance"
    | "circle_center_distance"
    | "circle_line_distance"
    | "point_distance";
  entityId: string;
  /** Raw label from C++ (e.g. "12.35 mm", "D 24.70 mm", "45\u00b0"). */
  label: string;
  /** Numeric value parsed from the C++ label (core mm or degrees). */
  rawValue: number;
  /** Unit suffix from the C++ label (e.g. " mm", "\u00b0", ""). */
  unitSuffix: string;
  isSelected: boolean;
  anchorStart: [number, number, number];
  anchorEnd: [number, number, number];
  dimensionStart: [number, number, number];
  dimensionEnd: [number, number, number];
  labelPosition: [number, number, number];

  // Angle arc geometry (from C++ core, for angle/line_angle kinds)
  arcCenter?: [number, number, number];
  arcRadius?: number;
  arcStartAngle?: number;
  arcEndAngle?: number;
  arcCcw?: boolean;

  // Reference line (from C++ core, for angle/line_angle kinds)
  refLineStart?: [number, number, number];
  refLineEnd?: [number, number, number];

  // When true, this is a reference (driven) dimension — the UI renders
  // it in parentheses like "(35mm)".
  driven?: boolean;

  /** Display variant: "x" = horizontal, "y" = vertical, "" = Euclidean
   *  for point_distance; "radius" / "diameter" for circle_radius. */
  displayAs?: string;
}

export interface SketchConstraintScene {
  constraintId: string;
  planeId: string;
  kind: ConstraintType;
  entityId: string;
  relatedEntityId: string | null;
  label: string;
  isSelected: boolean;
  position: [number, number, number];
  driven?: boolean;
}

export interface SketchProfileScene {
  profileId: string;
  planeId: string;
  planeFrame: {
    origin: [number, number, number];
    xAxis: [number, number, number];
    yAxis: [number, number, number];
    normal: [number, number, number];
  } | null;
  profileKind: "polygon" | "circle";
  profilePoints: [number, number][];
  innerLoops: [number, number][][];
  start: [number, number];
  width: number;
  height: number;
  radius: number;
  isSelected: boolean;
}

export interface SolidFaceScene {
  faceId: string;
  ownerId: string;
  ownerKind: string;
  label: string;
  sketchability: string;
  center: [number, number, number];
  normal: [number, number, number];
  planeFrame: {
    origin: [number, number, number];
    xAxis: [number, number, number];
    yAxis: [number, number, number];
    normal: [number, number, number];
  };
  size: { width: number; height: number; radius: number };
  // Body-derived faces ship a real per-face triangulation in world
  // space. The renderer turns this into a THREE.BufferGeometry so the
  // user picks the actual face shape (matters for booleaned, filleted,
  // and plane-frame-rotated faces). Empty for legacy analytical faces;
  // the renderer falls back to a (size, planeFrame) THREE.PlaneGeometry
  // in that case.
  trianglePositions: Float32Array;
  triangleIndices: Uint32Array;
  isSelected: boolean;
  appearanceColor: string | null;
}
