import * as THREE from "three";

import type {
  Vector3,
  SketchProfilePoint,
  PlaneOrientation,
  Axis,
  ConstraintType,
  PlaneFrame,
  SceneBounds,
  ScenePrimitive,
  SceneEdge,
  SceneVertex,
  CutPreviewScene,
  SolidFaceScene,
  SceneReference,
  SketchLineScene,
  SketchCircleScene,
  SketchArcScene,
  SketchDimensionScene,
  SketchConstraintScene,
  SketchVertexScene,
  SketchPolygonScene,
  SketchProfileScene,
  DocumentState,
} from "@/types";

export interface ViewportPlaneSize {
  width: number;
  height: number;
}

export interface ViewportBoxPrimitive {
  primitive_id: string;
  label: string;
  width: number;
  height: number;
  depth: number;
  x_offset: number;
  center: Vector3;
  is_selected: boolean;
  appearance_color: string | null;
}

export interface ViewportCylinderPrimitive {
  primitive_id: string;
  label: string;
  radius: number;
  height: number;
  x_offset: number;
  center: Vector3;
  plane_id: string;
  plane_frame: PlaneFrame | null;
  is_selected: boolean;
  appearance_color: string | null;
}

export interface ViewportPolygonExtrudePrimitive {
  primitive_id: string;
  label: string;
  plane_id: string;
  plane_frame: PlaneFrame | null;
  profile_points: SketchProfilePoint[];
  inner_loops: SketchProfilePoint[][];
  depth: number;
  is_selected: boolean;
  appearance_color: string | null;
}

export interface ViewportSolidFace {
  face_id: string;
  owner_id: string;
  owner_kind: string;
  label: string;
  sketchability: string;
  center: Vector3;
  normal: Vector3;
  plane_frame: PlaneFrame;
  size: {
    width: number;
    height: number;
    radius: number;
  };
  // Body-derived faces carry triangulation arrays; legacy analytical
  // faces leave these empty and the UI builds a pick mesh from
  // (size, plane_frame) instead.
  triangle_positions: number[];
  triangle_indices: number[];
  is_selected: boolean;
  appearance_color: string | null;
}

export interface ViewportReferencePlane {
  reference_id: string;
  label: string;
  orientation: PlaneOrientation;
  center: Vector3;
  size: ViewportPlaneSize;
  is_selected: boolean;
  is_active_sketch_plane: boolean;
  // Construction planes (parametric offset planes) ship a real
  // world-space frame here. Origin planes leave this null and the
  // renderer keeps using the legacy `orientation` rotation. Made
  // optional in TS so callers can omit it when constructing test
  // fixtures.
  plane_frame?: PlaneFrame | null;
}

export interface ViewportReferenceAxis {
  reference_id: string;
  label: string;
  axis: Axis | "custom";
  start: Vector3;
  end: Vector3;
}

export interface ViewportReferencePoint {
  reference_id: string;
  label: string;
  position: Vector3;
  is_selected: boolean;
}

export interface ViewportHelixPrimitive {
  helix_id: string;
  label: string;
  points: number[];
  is_selected: boolean;
}

export interface ViewportSketchLine {
  line_id: string;
  start_vertex_id: string;
  end_vertex_id: string;
  plane_id: string;
  start: Vector3;
  end: Vector3;
  is_selected: boolean;
  constraint: ConstraintType | null;
  is_construction: boolean;
  // True for transient lines generated by the in-progress Mirror
  // tool. Defaults to false in the schema for back-compat.
  is_preview: boolean;
  // Set for glyph segments expanded from a sketch text entry
  // ("text:<text-id>"). Null for hand-drawn / projected lines;
  // defaults to null in the schema for back-compat.
  generated_by: string | null;
}

export interface ViewportSketchCircle {
  circle_id: string;
  plane_id: string;
  plane_frame: PlaneFrame | null;
  center: Vector3;
  radius: number;
  is_selected: boolean;
  is_construction: boolean;
  is_preview: boolean;
  // See `ViewportSketchLine.generated_by` (reserved — the v1 text
  // expansion only emits lines).
  generated_by: string | null;
}

export interface ViewportSketchPolygon {
  polygon_id: string;
  plane_id: string;
  plane_frame: PlaneFrame | null;
  corner_x: number[];
  corner_y: number[];
  corner_z: number[];
  sides: number;
  mode: string;
  center: Vector3;
  radius: number;
  is_selected: boolean;
  is_construction: boolean;
  is_preview: boolean;
}

// 2D arc primitive emitted by the core. Carries world-space start /
// end / center coordinates plus the radius and ccw flag so the UI
// renderer can sample the polyline locally without having to know
// about the sketch plane orientation.
export interface ViewportSketchArc {
  arc_id: string;
  start_vertex_id: string;
  end_vertex_id: string;
  plane_id: string;
  plane_frame: PlaneFrame | null;
  center: Vector3;
  radius: number;
  start: Vector3;
  end: Vector3;
  ccw: boolean;
  is_selected: boolean;
  is_construction: boolean;
  is_preview: boolean;
  // See `ViewportSketchLine.generated_by` (reserved — the v1 text
  // expansion only emits lines).
  generated_by: string | null;
}

export interface ViewportSketchVertex {
  /** vertex-N ID from Phase 4 vertex unification. */
  vertex_id: string;
  plane_id: string;
  // "endpoint" — line / arc endpoint (default).
  // "center" — circle center.
  // "projected" — Project-tool result; locked, drawn distinctly.
  // "quadrant" — derived cardinal point on a circle perimeter.
  kind: "endpoint" | "center" | "projected" | "quadrant" | "fillet_corner";
  position: Vector3;
  is_fixed: boolean;
  is_selected: boolean;
  // ── Vertex unification (Phase 1) ───────────────────────────
  geometry_owner_ids?: string[];
  is_projected?: boolean;
  source_type?: string;
  source_feature_id?: string;
  source_edge_id?: string;
}

export interface ViewportSketchDimension {
  dimension_id: string;
  plane_id: string;
  kind:
    | "line_length"
    | "circle_radius"
    | "arc_radius"
    | "polygon_radius"
    | "angle"
    | "line_angle"
    | "line_line_distance"
    | "circle_center_distance"
    | "circle_line_distance"
    | "point_distance";
  entity_id: string;
  label: string;
  is_selected: boolean;
  anchor_start: Vector3;
  anchor_end: Vector3;
  dimension_start: Vector3;
  dimension_end: Vector3;
  label_position: Vector3;

  // Angle arc geometry (from C++ core, optional)
  arc_center?: Vector3;
  arc_radius?: number;
  arc_start_angle?: number;
  arc_end_angle?: number;
  arc_ccw?: boolean;

  // Reference line (from C++ core, optional)
  ref_line_start?: Vector3;
  ref_line_end?: Vector3;

  // Display variant: "x" = horizontal, "y" = vertical, "" = Euclidean
  display_as?: string;

  driven?: boolean;
}

export interface ViewportSketchConstraint {
  constraint_id: string;
  plane_id: string;
  kind: ConstraintType;
  entity_id: string;
  related_entity_id: string | null;
  label: string;
  is_selected: boolean;
  position: Vector3;
  driven?: boolean;
}

export interface ViewportSketchProfile {
  profile_id: string;
  plane_id: string;
  plane_frame: PlaneFrame | null;
  profile_kind: "polygon" | "circle";
  profile_points: SketchProfilePoint[];
  inner_loops: SketchProfilePoint[][];
  start_x: number;
  start_y: number;
  width: number;
  height: number;
  radius: number;
  is_selected: boolean;
}

export interface ViewportSceneBounds {
  center: Vector3;
  size: Vector3;
  max_dimension: number;
}

export interface ViewportScene {
  bounds: SceneBounds;
  primitives: ScenePrimitive[];
  solidFaces: SolidFaceScene[];
  edges: SceneEdge[];
  vertices: SceneVertex[];
  cutPreviews: CutPreviewScene[];
  references: SceneReference[];
  sketchLines: SketchLineScene[];
  sketchCircles: SketchCircleScene[];
  sketchPolygons: SketchPolygonScene[];
  sketchArcs: SketchArcScene[];
  sketchDimensions: SketchDimensionScene[];
  sketchConstraints: SketchConstraintScene[];
  sketchPoints: SketchVertexScene[];
  sketchProfiles: SketchProfileScene[];
  geometryKey: string;
}

export interface PrimitiveVisual {
  baseMaterial: THREE.MeshStandardMaterial;
  edgeMaterial: THREE.LineBasicMaterial;
  appearanceColor: string | null;
}

export interface ReferencePlaneVisual {
  fillMaterial: THREE.MeshBasicMaterial;
  edgeMaterial: THREE.LineBasicMaterial;
}

export interface PrimitiveInteractionState {
  isSelected: boolean;
  isHovered: boolean;
}

export interface ReferencePlaneInteractionState {
  isSelected: boolean;
  isHovered: boolean;
  isActiveSketchPlane: boolean;
}

export interface SolidFaceVisual {
  fillMaterial: THREE.MeshBasicMaterial;
  appearanceColor: string | null;
}

export interface SolidFaceInteractionState {
  isSelected: boolean;
  isHovered: boolean;
}

export interface SketchProfileVisual {
  fillMaterial: THREE.MeshBasicMaterial;
  /** Edge materials for the profile's outer contour. */
  edgeMaterials: THREE.LineBasicMaterial[];
  /** Edge materials for the profile's inner loops (holes). */
  holeEdgeMaterials: THREE.LineBasicMaterial[];
}

export interface SketchProfileInteractionState {
  isSelected: boolean;
  isHovered: boolean;
}

export interface ViewportContextMenuState {
  x: number;
  y: number;
  referenceId: string | null;
  faceId: string | null;
  bodyId?: string | null;
  sketchDeleteSelection?: {
    entityIds: string[];
    vertexIds: string[];
    profileIds: string[];
  } | null;
  dimensionId?: string | null;
  // Set when right-clicking a single sketch line so the context menu
  // can offer "Toggle Construction" in addition to Delete.
  lineId?: string | null;
  // Constraint right-click → Delete:
  // Set when user right-clicks a constraint badge.
  constraintKind?: string;
  constraintId?: string;
  constraintEntityId?: string;
  constraintRelatedEntityId?: string | null;
}

interface SketchEntityInteractionState {
  isSelected: boolean;
  isHovered: boolean;
}

export interface SketchPreviewPoint {
  local: [number, number];
  world: [number, number, number];
  snapLabel: string | null;
  snapFeedbackSource?: "object" | "grid" | null;
  snapTargetKey?: string | null;
  // When the resolved point snapped to a midpoint snap target, this
  // is the host line's id; the line tool uses it to attach a midpoint
  // anchor after the line is committed. Null for endpoint / origin /
  // circle-center / no-snap resolutions.
  snapMidpointHostLineId?: string | null;
  // Parametric position along `snapMidpointHostLineId` for the
  // resolved midpoint. 0.5 for a whole-line midpoint; some other
  // value when the host line has been "split" by an intermediate
  // anchored point (a quarter-line, eighth-line, etc. snap).
  // Drives the anchor choice on commit: t==0.5 → midpoint anchor,
  // otherwise → point_line anchor.
  snapMidpointT?: number | null;
  // Set when the cursor was projected onto a perpendicular ray
  // emanating from the line draft's start (because the start lay on
  // an existing line). The post-commit step uses this to apply a
  // perpendicular constraint between the new line and the host line.
  snapPerpendicularHostLineId?: string | null;
  // The host line id of the line whose endpoint the start of the
  // draft snapped to. Carried on every resolved point so the pointer
  // handler can stash it as the perpendicular reference for the
  // remaining draft clicks. Distinct from `snapPerpendicularHostLineId`,
  // which only lights up when the *current* cursor is on the perp ray.
  snapEndpointHostLineId?: string | null;
  // When the resolved point snapped to a line's body (anywhere along
  // the segment, not just an endpoint or midpoint), this holds the
  // host line id and the parametric position `t` in [0, 1] along it.
  // The post-commit step uses these to attach a `point_line_anchor`
  // so the bound point rides with the host as it edits.
  snapLineBodyHostLineId?: string | null;
  snapLineBodyT?: number | null;
  // When the cursor snapped to the nearest point on a circle's perimeter,
  // this holds the host circle id and the angle (in radians) of the snapped
  // point relative to the circle center.
  snapCircleBodyHostCircleId?: string | null;
  snapCircleBodyAngle?: number | null;
  // When the cursor was within the angular threshold of the world X
  // or Y axis relative to the draft start, the resolver pulls the
  // off-axis coordinate onto the start to lock the segment flat. The
  // post-commit step uses this kind to apply a `set_sketch_line_constraint`
  // of "horizontal" or "vertical" to the new line.
  snapAxisLock?: "horizontal" | "vertical" | null;
  // When the cursor snapped onto one of the two tangent points from
  // the draft start to a circle's circumference, this holds the
  // host circle id. The post-commit step uses it to add a
  // `tangent_line_circle` relation between the new line and the
  // circle so the line stays tangent through later edits.
  snapTangentCircleId?: string | null;
  /** When tangent snap fires, the exact contact point [x, y] on the
   *  circle where the tangent line touches. Used at commit time to
   *  set the next polyline segment start to the solver-resolved
   *  position rather than the cursor-projected snap position. */
  snapTangentPoint?: [number, number] | null;
  // When the cursor landed on a parallel projection from the draft
  // start relative to an existing line, this holds the host line id.
  // The post-commit step uses it to apply a
  // `set_sketch_parallel_constraint` between the new line and the
  // host line so the line stays parallel through later edits.
  snapParallelHostLineId?: string | null;
  // When the cursor snapped to the intersection of two sketch lines
  // (via multi-constraint speculative solve), this holds the pair of
  // intersecting line IDs. The post-commit step can use these to
  // attach coincident constraints to both lines at the intersection
  // point. Null when not at an intersection.
  snapIntersectionLineIds?: [string, string] | null;
  /** Dotted inference guide lines to render during line drafting.
   *  When the cursor aligns horizontally or vertically with an existing
   *  sketch vertex, a guide line is drawn from that vertex to the
   *  snapped draft position. Multiple guides may be active at once. */
  inferenceLines?: Array<{
    from: [number, number];
    draft: [number, number];
    axis: "horizontal" | "vertical";
  }>;
}

export type SketchPlaneFrame = NonNullable<
  NonNullable<
    NonNullable<
      DocumentState["feature_history"][number]["sketch_parameters"]
    >["plane_frame"]
  >
>;

export type SolidFacePlaneFrame = SolidFaceScene["planeFrame"];
