#pragma once

#include <optional>
#include <string>
#include <vector>
#include "core/sketch/sketch_profile.h"
#include "core/viewport/viewport_solid_primitives.h"

namespace polysmith::core {

struct ViewportSketchLinePrimitive {
  std::string line_id;
  std::string start_vertex_id;
  std::string end_vertex_id;
  std::string plane_id;
  double start_x;
  double start_y;
  double start_z;
  double end_x;
  double end_y;
  double end_z;
  bool is_selected;
  std::optional<std::string> constraint;
  bool is_construction = false;
  // True for entities generated by the in-progress Mirror tool
  // (`pending_mirror.generated_lines`). The UI renders them as a
  // dashed translucent preview; they're not selectable, not
  // hover-targetable, and don't appear in the points/dimensions
  // arrays. False for committed sketch lines.
  bool is_preview = false;
  std::string dof_status;
};

struct ViewportSketchCirclePrimitive {
  std::string circle_id;
  std::string plane_id;
  std::optional<ViewportSketchPlaneFrame> plane_frame;
  double center_x;
  double center_y;
  double center_z;
  double radius;
  bool is_selected;
  bool is_construction = false;
  // See `ViewportSketchLinePrimitive::is_preview`.
  bool is_preview = false;
  std::string dof_status;
};

// 2D arc primitive emitted to the viewport. Carries the arc's
// endpoints and center in world coordinates plus its radius and ccw
// flag so the renderer can sample the polyline locally without
// re-projecting back through the sketch plane. Endpoint world
// coordinates are kept alongside `start_point_id` / `end_point_id`
// so consumers (snapping, highlights) can look up the same shared
// SketchVertex that lines use without an extra lookup.
struct ViewportSketchArcPrimitive {
  std::string arc_id;
  std::string start_vertex_id;
  std::string end_vertex_id;
  std::string plane_id;
  std::optional<ViewportSketchPlaneFrame> plane_frame;
  double center_x;
  double center_y;
  double center_z;
  double radius;
  double start_x;
  double start_y;
  double start_z;
  double end_x;
  double end_y;
  double end_z;
  bool ccw;
  bool is_selected;
  bool is_construction = false;
  // See `ViewportSketchLinePrimitive::is_preview`.
  bool is_preview = false;
  std::string dof_status;
};

struct ViewportSketchVertexPrimitive {
  std::string vertex_id;
  std::string plane_id;
  std::string kind;
  double position_x;
  double position_y;
  double position_z;
  bool is_fixed;
  bool is_selected;
  std::string dof_status;

  // ── Vertex unification fields (Phase 1) ─────────────────────
  std::vector<std::string> geometry_owner_ids;
  bool is_projected = false;
  std::optional<std::string> source_type;
  std::optional<std::string> source_feature_id;
  std::optional<std::string> source_edge_id;
};

struct ViewportSketchDimensionPrimitive {
  std::string dimension_id;
  std::string plane_id;
  std::string kind;
  std::string entity_id;
  std::string label;
  bool is_selected;
  double anchor_start_x;
  double anchor_start_y;
  double anchor_start_z;
  double anchor_end_x;
  double anchor_end_y;
  double anchor_end_z;
  double dimension_start_x;
  double dimension_start_y;
  double dimension_start_z;
  double dimension_end_x;
  double dimension_end_y;
  double dimension_end_z;
  double label_x;
  double label_y;
  double label_z;

  // Angle arc geometry (for angle/line_angle kinds; zero otherwise)
  double arc_center_x = 0.0;
  double arc_center_y = 0.0;
  double arc_center_z = 0.0;
  double arc_radius = 0.0;
  double arc_start_angle = 0.0;  // radians
  double arc_end_angle = 0.0;    // radians
  bool arc_ccw = false;

  // Reference line (for angle/line_angle kinds; zero otherwise)
  double ref_line_start_x = 0.0;
  double ref_line_start_y = 0.0;
  double ref_line_start_z = 0.0;
  double ref_line_end_x = 0.0;
  double ref_line_end_y = 0.0;
  double ref_line_end_z = 0.0;

  // When true, this is a reference (driven) dimension. The UI renders
  // it in parentheses like "(35mm)" to distinguish from driving dims.
  bool driven = false;

  // Display variant: for point_distance, "x" = horizontal, "y" = vertical,
  // "" = Euclidean.  For circle_radius, "radius" or "diameter".
  std::string display_as;
};

struct ViewportSketchConstraintPrimitive {
  std::string constraint_id;
  std::string plane_id;
  std::string kind;
  std::string entity_id;
  std::optional<std::string> related_entity_id;
  std::string label;
  bool is_selected;
  double position_x;
  double position_y;
  double position_z;
  // When true, this is a reference (driven) constraint.
  // The UI renders it in parentheses like "(V)" to distinguish
  // from driving constraints.
  bool driven = false;
};

struct ViewportSketchPolygonPrimitive {
  std::string polygon_id;
  std::string plane_id;
  std::optional<ViewportSketchPlaneFrame> plane_frame;
  // World-space corner positions as a flat xyzw list for each corner.
  std::vector<double> corner_x;
  std::vector<double> corner_y;
  std::vector<double> corner_z;
  int sides;
  std::string mode;
  double center_x;
  double center_y;
  double center_z;
  double radius;
  bool is_selected;
  bool is_construction = false;
  bool is_preview = false;
  std::string dof_status;
};

struct ViewportSketchProfilePrimitive {
  std::string profile_id;
  std::string plane_id;
  std::optional<ViewportSketchPlaneFrame> plane_frame;
  std::string profile_kind;
  std::vector<SketchProfilePoint> profile_points;
  std::vector<std::vector<SketchProfilePoint>> inner_loops;
  double start_x;
  double start_y;
  double width;
  double height;
  double radius;
  bool is_selected;
};

}  // namespace polysmith::core
